import ProductsPage from "../pages/ProductsPage";
import HomePage from "../pages/HomePage";
import AboutPage from "../pages/AboutPage";
import NotFoundPage from "../pages/NotFoundPage";
import type { AppState } from "../types";
import { state } from "../services/store/store";
import { lazyLoadImgs } from "../utils/lazy-load-img";

const PATHS = {
  home: {
    url: "/",
    component: HomePage,
  },
  products: {
    url: "/products",
    component: ProductsPage,
  },
  about: {
    url: "/about",
    component: AboutPage,
  },
  // profile: {
  //   url: "/profile",
  //   component: ProfilePage,
  // },
} as const;

/**
 * Handles routing logic for the application by matching the current path to a route definition.
 *
 * @param currentPath - The current URL path to match against the route definitions.
 * @param routes - An object containing route definitions, where each route has a `url` and a `component`.
 * @param state - The current application state to be passed to the route's component.
 * @returns The HTML string generated by the matched route's component, or the NotFoundPage if no match is found.
 */
export default async function router(
  currentPath = "",
  state: AppState,
  routes = PATHS
): Promise<string> {
  // Find the matching route by path
  const currentRoute = Object.values(routes).find(
    (route) => route.url === currentPath
  );

  let html = await NotFoundPage();

  if (currentRoute) {
    html = await currentRoute.component(state);
  }

  return html;
}

export async function renderRoute(path?: string | undefined) {
  path = path ?? window.location.pathname;
  // Get the element where content will be rendered
  const contentContainer = document.getElementById("app-content");

  if (!path || !contentContainer) return;

  contentContainer.innerHTML = await router(path, state);

  // Run any code that needs DOM elements here after route render;
  lazyLoadImgs();
}
